### PR TITLE
Fixes needed for packaging

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Does it make sense to include the Gemfile in the gem itself? It was only intended for development use, and I really didn't want that to have to end up in the RPM package.

**Comment by jlsherrill** [comment]
@stbenjam i think it was likely not intentional.  ACK

**Comment by stbenjam** [comment]
Needed another change, ssh.yml doesn't follow convention.

**Comment by jlsherrill** [comment]
ACK

**Pull request merged**
