### PR TITLE
MQTT rate limitting

### PR DESCRIPTION
**Pull request by adamruzicka**
The previously opened PR https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/90 wasn't really solving anything as it did rate limitting *after* the notifications were already sent.

### CODE REVIEW

**Comment by sjha4** [comment]
@adamruzicka : Could you add some testing steps and context behind this change.

**Comment by adamruzicka** [comment]
> context behind this change

We need to have a way of rate-limitting jobs that are handed out to the clients. If you run a sufficienlty large job, it might happen that the clients will hit the smart proxy so hard that some of them either won't get the job or will fail to report progress back to the proxy. To the user, it will appear that the job "got stuck".

> some testing steps

Prerequisites:
- Foreman with rex with proxy in pull-mqtt mode
- At least 2 clients

Actual steps:
- Bump yggdrasil log level to debug on clients
- Set mqtt_rate_limit to 1 in sp-rex-ssh config
- Run a job that takes some time (like sleep 60) on both hosts at once

Expected results:
- The job is executed on the hosts sequentially (watch yggdrasild logs on clients, compare timestamps)

Of course those are the most basic steps and this this should be tested at scale, which non of us really have means for. OTOH Satellite perf team already took this for a spin. Runnning a job without this patch on 6975 hosts resulted in 2800 "getting stuck", running the same job with rate_limit set to 800 resulted in "only" ~200 getting stuck.

**Comment by jeremylenz** [comment]
[test smart_proxy_remote_execution_ssh]

**Comment by jeremylenz** [comment]
After hacking my way through some [Bundler hell](https://paste.centos.org/view/35ef6456), I thought I had successfully checked out the repo from source, but alas, the server won't start with this PR checked out:

I also checked out `smart_proxy_dynflow` from source, but same result.

Switching back to the gem version the server starts fine.

```
22:07:39 rails.1   | /home/vagrant/smart_proxy_dynflow/lib/smart_proxy_dynflow/callback.rb:5:in `<module:Callback>': uninitialized constant Proxy::HttpRequest (NameError)
22:07:39 rails.1   | 	from /home/vagrant/smart_proxy_dynflow/lib/smart_proxy_dynflow/callback.rb:4:in `<module:Dynflow>'
22:07:39 rails.1   | 	from /home/vagrant/smart_proxy_dynflow/lib/smart_proxy_dynflow/callback.rb:3:in `<main>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
22:07:39 rails.1   | 	from /home/vagrant/smart_proxy_dynflow/lib/smart_proxy_dynflow.rb:10:in `<main>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
22:07:39 rails.1   | 	from /home/vagrant/smart_proxy_remote_execution_ssh/lib/smart_proxy_remote_execution_ssh.rb:1:in `<main>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:64:in `block (2 levels) in require'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:59:in `each'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:59:in `block in require'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `each'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `require'
22:07:39 rails.1   | 	from /usr/share/gems/gems/bundler-2.2.24/lib/bundler.rb:174:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/config/application.rb:58:in `<main>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:138:in `block in perform'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `tap'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/commands/server/server_command.rb:135:in `perform'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/command/base.rb:69:in `perform'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/command.rb:48:in `invoke'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/railties-6.1.7/lib/rails/commands.rb:18:in `<main>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/bin/rails:9:in `<top (required)>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
22:07:39 rails.1   | 	from /home/vagrant/foreman/.vendor/ruby/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
22:07:39 rails.1   | 	from /home/vagrant/foreman/bin/spring:13:in `require'
22:07:39 rails.1   | 	from /home/vagrant/foreman/bin/spring:13:in `<top (required)>'
22:07:39 rails.1   | 	from bin/rails:3:in `load'
22:07:39 rails.1   | 	from bin/rails:3:in `<main>'
22:07:39 rails.1   | exited with code 1
22:07:39 system    | sending SIGTERM to all processes
22:07:44 system    | sending SIGKILL to all processes
```

**Comment by adamruzicka** [comment]
That looks like you're trying to load a smart proxy plugin into foreman itself?

**Comment by jeremylenz** [comment]
> That looks like you're trying to load a smart proxy plugin into foreman itself?

yep, that was it!  All sorted now..

**Review by jeremylenz — APPROVED** [review]
Without this change, jobs run concurrently as expected.

Tested with `mqtt_rate_limit` of 1 and jobs run sequentially on hosts as expected:

```
Nov 30 19:14:52 rhel8b.fedora.example.com yggdrasild[12655]: [yggdrasild] 2022/11/30 19:14:52 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/11/30 19:14:52 started script process: 13720
Nov 30 19:15:07 rhel8b.fedora.example.com yggdrasild[12655]: [yggdrasild] 2022/11/30 19:15:07 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/11/30 19:15:07 Finished job 0bb12afd-4937-4c34-a4c8-ea59a61a0872
------------------------
Nov 30 19:15:07 rhel8c.fedora.example.com yggdrasild[4010]: [yggdrasild] 2022/11/30 19:15:07 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/11/30 19:15:07 started script process: 18430
Nov 30 19:15:22 rhel8c.fedora.example.com yggdrasild[4010]: [yggdrasild] 2022/11/30 19:15:22 [/usr/libexec/yggdrasil/foreman_ygg_worker] 2022/11/30 19:15:22 Finished job f4642672-6467-428c-aa3e-4a654eca49fc
```

LGTM! thanks @iballou and @adamruzicka for the help

ACK :+1:

**Comment by adamruzicka** [comment]
Thank you @jeremylenz !

**Pull request merged**
