### PR TITLE
Refs #15214 - Added setting for ssh port - belongs to PR #196 foreman…

### PR DESCRIPTION
**Pull request by TuningYourCode**
Belongs to https://github.com/theforeman/foreman_remote_execution/pull/196

### CODE REVIEW

**Comment by iNecas** [comment]
Thanks @TuningYourCode  Looks nice so far. It would be beneficial to also add a test similar to the ssh_user part. I've just merged a PR that fixes the tests in master so the jenkins should be running the tests as well in a while.

**Comment by iNecas** [comment]
I've created a separate issue for the smart proxy and linked to the original issue http://projects.theforeman.org/issues/16018 so that we can track what version of this gem it was fixed in and we make sure both gems are released properly. Please updated the commit message to link to the new issue.

**Comment by TuningYourCode** [comment]
Sorry, fucked this one a little bit up. Would be great if you could take the other one which referes the new issue in your bugtracker :)

**Comment by iNecas** [comment]
You can just use `git rebase -i` to update the history and force push to your remote branch and it should update here.

**Comment by iNecas** [comment]
[test]

**Comment by TuningYourCode** [comment]
After some trouble the commit should be now have a proper commit message :)

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
Tests are failing now, probably this needs to be updated https://github.com/theforeman/smart_proxy_remote_execution_ssh/blob/master/test/core/support/dummy_connector.rb#L8

**Comment by TuningYourCode** [comment]
Sorry for the delay but i couldn't get the tests running and there are no instructions to get them running :(

Made some changes to the commit so that there should no changes to the test suite be needed.

**Comment by stbenjam** [comment]
[test]

**Comment by iNecas** [comment]
Merged as 618379fa62888966f0cae5a0346c2ce784b4d1a4, thanks @TuningYourCode and contgratulations to the first contribution to the Foreman ecosystem, looking forward to hear more from you in the future :)

**Pull request closed without merging**
