### PR TITLE
fixes #15335 - create bundler.d for core

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
@adamruzicka This one needs an ACK too when you have a minute

**Comment by adamruzicka** [comment]
@stbenjam Oh, right, sorry to keep you waiting. Let's get it in, ACK

**Comment by stbenjam** [comment]
Oh awesome, thanks!!

**Comment by adamruzicka** [comment]
Wow, that was quick

**Pull request merged**
