### PR TITLE
Fixes #11849 - sanitize script to handle carriage returns properly

### PR DESCRIPTION
**Pull request by iNecas**

### CODE REVIEW

**Comment by ares** [comment]
Tests are red on 2.1

```
  1) Error:
killing#test_0001_sends pkill to the send signal to the remote process:
RuntimeError: Error waiting for dummy connector to finish
    /var/lib/workspace/workspace/test_proxy_plugin_pull_request/ruby/2.1/test/support/dummy_connector.rb:77:in `wait'
    /var/lib/workspace/workspace/test_proxy_plugin_pull_request/ruby/2.1/test/dispatcher_test.rb:127:in `block (2 levels) in <class:DispatcherTest>'
```

**Comment by iNecas** [comment]
[test]

**Comment by iNecas** [comment]
Tests are green

**Comment by adamruzicka** [comment]
ACK

**Comment by iNecas** [comment]
Thanks @adamruzicka

**Pull request merged**
