### PR TITLE
Update to bundler.d to match other smart proxy plugins

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
[test smart_proxy_remote_execution_ssh]

**Comment by adamruzicka** [comment]
I'm still not convinced this is a good idea. Usually for a project X `bundler.d` and files inside it allow declaring additional gems as dependencies of project X. Since this is a plugin, those two files are used to declare this plugin and its dependency as dependencies for the smart proxy. I'd say it would make things even more confusing if we moved everything to bundler.d

Furthermore, this would declare `smart_proxy_remote_execution_ssh` as dependency of `smart_proxy_remote_execution_ssh` and this plugin only looks at `Gemfile.local.rb`, not at contents of `bundler.d`

**Comment by adamruzicka** [comment]
Now's the time to do this. @ehelms could you drop `bundler.d/foreman_remote_execution_core.rb` while you're at it?

**Comment by ehelms** [comment]
Done

**Review by adamruzicka — APPROVED** [review]

**Comment by adamruzicka** [comment]
Thank you @ehelms!

**Pull request merged**
